### ISSUE TITLE
fails to parse attributes with line feeds

### ISSUE THREAD

**Issue by btbonval** [jhuckaby/pixl-xml#2]
I have XML which can be parsed by libxml2, but pixl-xml version 1.0.1 throws a ParseError that looks like this:

```
Error: Parse Error: Malformed tag on line 254: <bind calculate="if ( /assessment/group_cough/patient_coughs ='yes', 
 concat (
...
)" nodeset="/assessment/outputs/symptom_cough" type="string"/>
    at XML.throwParseError (/storage/development/git-repo/medic-analytics/node_modules/pixl-xml/xml.js:246:8)
    at XML.parse (/storage/development/git-repo/medic-analytics/node_modules/pixl-xml/xml.js:131:10)
    at XML.parse (/storage/development/git-repo/medic-analytics/node_modules/pixl-xml/xml.js:178:11)
    at XML.parse (/storage/development/git-repo/medic-analytics/node_modules/pixl-xml/xml.js:178:11)
    at XML.parse (/storage/development/git-repo/medic-analytics/node_modules/pixl-xml/xml.js:178:11)
    at new XML (/storage/development/git-repo/medic-analytics/node_modules/pixl-xml/xml.js:62:22)
    at Object.parse_xml [as parse] (/storage/development/git-repo/medic-analytics/node_modules/pixl-xml/xml.js:410:15)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
```

I'm not sure how much of the raw XML I can share, but hopefully that is enough of an example to demonstrate line feeds in an attribute.

When I edit the XML and remove all line feeds so that `<bind calculate='...` is on the same line as `... nodeset="..." type="string"/>`, then pixl-xml can parse the file without error.

**Comment by btbonval** [comment]
Workaround that is successful for me:

Instead of `XML.parse( xml_string );`, I had success with `XML.parse( xml_string.replace(/\r|\n/g, ' ') )` to create a single line of XML. This might not be a valid workaround if line feeds must be preserved in attributes or text elements. Thankfully that is not important for what I need to do.

**Comment by jhuckaby** [comment]
Thank you for this bug report @btbonval.  To be honest, I had no idea line feeds were even allowed in XML attributes.  15 years of using XML professionally and I've never seen them --- hahahaha!  I will fix this as soon as possible.

Glad to hear your workaround works in the interim.

\- Joe

**Comment by btbonval** [comment]
@jhuckaby Much appreciated. This library is fantastic by the way. I was briefly looking for alternative libraries to deal with this particular issue, but I'm so glad I could find a workaround.

I don't know too much about XML specifications personally. My supervisor told me that the spaces are indeed allowed in the specs, but I haven't read that myself. If it helps for any reason, I'm dealing with OpenRosa forms. https://opendatakit.org/help/form-design/

Of course, none of the examples on that page contain line feeds...

**Comment by jhuckaby** [comment]
Fixed in https://github.com/jhuckaby/pixl-xml/commit/334ccbdd629bbe507a4e9bc2373af2c8ee7cc356

Tagged [v1.0.6](https://github.com/jhuckaby/pixl-xml/releases/tag/v1.0.6).

Thanks again!

\- Joe

**Comment by btbonval** [comment]
Thank you for the fix!
